micronaut:
  application:
    name: videogame-leader-board-service

kafka:
  bootstrap:
    servers: localhost:9092
    streams:
      default:
        num.stream.threads: 10
# kafka.streams.default.state.dir=/tmp

endpoints:
  health:
    details-visible: ANONYMOUS